#!/bin/sh

case "$1" in
  up)
    pamixer -i 5 --allow-boost --set-limit 150
    ;;
  down)
    pamixer -d 5 --allow-boost --set-limit 150
    ;;
  mute)
    pamixer -t
    ;;
  *)
    echo "Usage: $0 {up|down|mute}" >&2
    exit 1
    ;;
esac

notify-send -r 100 -t 1500 "Volume: $(pamixer --get-volume-human)"

